### ISSUE TITLE
Rate limit handling

### ISSUE THREAD

**Issue by scalp42** [cAttte/reddit-migrate#2]
hi @cAttte 

Thanks for the tool! I just tested and unfortunately, it doesn't seem to handle rate limiting:

```
Unexpected Error: snoowrap refused to continue because reddit's ratelimit was exceeded. For more information about reddit's ratelimit, please consult reddit's API rules at https://github.com/reddit/reddit/wiki/API.
```

Do you have any plans to support it?

Thanks in advance

**Comment by cAttte** [comment]
hey! sorry for such a late response. i thought snoowrap would handle ratelimiting (like most API wrappers), and i never ran into any ratelimit problems while testing, but i'll check out the docs and fix it asap, thanks for reporting this!

**Comment by cAttte** [comment]
sorry for fixing this after 2 months, but snoowrap *does* have ratelimit handling, it just needed the `continueAfterRatelimitError` option enabled.
